# Generated by Django 4.2 on 2023-04-27 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeNewsDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(max_length=500)),
                ('content', models.TextField()),
                ('classification', models.CharField(max_length=10)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=500)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetricsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=5)),
                ('model', models.TextField(max_length=50)),
                ('algoritm', models.TextField(max_length=50)),
                ('accuracy', models.DecimalField(decimal_places=3, max_digits=3)),
                ('recall', models.DecimalField(decimal_places=3, max_digits=3)),
                ('precision', models.DecimalField(decimal_places=3, max_digits=3)),
                ('errorRate', models.DecimalField(decimal_places=3, max_digits=3)),
                ('f1score', models.DecimalField(decimal_places=3, max_digits=3)),
                ('logloss', models.DecimalField(decimal_places=3, max_digits=3)),
                ('auc', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdministrator', models.BooleanField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
