# Generated by Django 4.2 on 2023-04-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_feedbackuser_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='isAdministrator',
            field=models.BooleanField(default=False),
        ),
    ]
