# Generated by Django 4.1.9 on 2023-06-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_useraccount_isadministrator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
