# Generated by Django 4.1.9 on 2023-06-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_useraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricsmodel',
            name='model',
        ),
    ]
