# Generated by Django 4.1.9 on 2023-06-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_algoritm_metricsmodel_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackuser',
            name='name',
            field=models.TextField(default='Não informado', max_length=500),
        ),
        migrations.AddField(
            model_name='feedbackuser',
            name='username',
            field=models.TextField(default='Não informado', max_length=100),
        ),
    ]
