# Generated by Django 4.1.9 on 2023-06-07 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_feedbackuser_name_feedbackuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakenewsdetection',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
