# Generated by Django 4.1.9 on 2023-06-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_fakenewsdetection_confidence_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakenewsdetectiondetail',
            old_name='news',
            new_name='news_id',
        ),
    ]
