# Generated by Django 4.1.9 on 2023-06-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_news_fakenewsdetectiondetail_news_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fakenewsdetectiondetail',
            old_name='news_id',
            new_name='news',
        ),
    ]
