# Generated by Django 4.1.9 on 2023-06-09 22:20

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_news_id_fakenewsdetectiondetail_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakenewsdetectiondetail',
            name='date',
            field=models.DateTimeField(default=app.models.get_current_date),
        ),
        migrations.AddField(
            model_name='fakenewsdetectiondetail',
            name='review',
            field=models.IntegerField(default=0),
        ),
    ]
